import { Component, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { AcademicCatalog, ApiService, AttendanceRecord } from '../../core/services/api.service';
import { PageHeaderComponent } from '../../shared/components/page-header/page-header.component';

@Component({
  standalone: true,
  imports: [FormsModule, PageHeaderComponent],
  template: `<app-page-header title="Asistencia" description="Registra y corrige la asistencia del aula para una fecha." /><section class="panel filters"><label>Nivel<select [(ngModel)]="level" (ngModelChange)="gradeId = ''; sectionId = ''; courseId = ''; loadCatalog()"><option value="">Seleccionar nivel</option>@for (item of levels(); track item) {<option [value]="item">{{ item }}</option>}</select></label><label>Grado<select [(ngModel)]="gradeId" (ngModelChange)="sectionId = ''; courseId = ''; loadCatalog()" [disabled]="!level"><option value="">Seleccionar grado</option>@for (grade of gradesForLevel(); track grade.id) {<option [value]="grade.id">{{ grade.name }}</option>}</select></label><label>Sección<select [(ngModel)]="sectionId" (ngModelChange)="courseId = ''; loadCatalog()" [disabled]="!gradeId"><option value="">Seleccionar sección</option>@for (section of sectionsForGrade(); track section.id) {<option [value]="section.id">{{ gradeName(section.grade_id) }} · {{ section.name }}</option>}</select></label><label>Curso<select [(ngModel)]="courseId" (ngModelChange)="loadRecords()" [disabled]="!sectionId"><option value="">Seleccionar curso</option>@for (course of catalog().courses; track course.id) {<option [value]="course.id">{{ course.name }}</option>}</select></label><label>Periodo<select [(ngModel)]="periodId" (ngModelChange)="loadRecords()" [disabled]="!sectionId"><option value="">Seleccionar periodo</option>@for (period of catalog().periods; track period.id) {<option [value]="period.id">{{ period.name }}</option>}</select></label><label>Fecha<input type="date" [(ngModel)]="attendanceDate" (ngModelChange)="loadRecords()" /></label></section>@if (!sectionId || !courseId || !periodId) {<p class="panel">Selecciona grado, sección, curso y periodo para cargar la lista del aula.</p>} @else {<section class="summary"><span>Presentes: {{ count('PRESENT') }}</span><span>Faltas: {{ count('ABSENT') }}</span><span>Tardanzas: {{ count('LATE') }}</span></section><section class="panel"><div class="quick"><button type="button" (click)="markAll('PRESENT')">Todos presentes</button><button type="button" class="outline" (click)="markAll('ABSENT')">Todos ausentes</button></div><table><thead><tr><th>Estudiante</th><th>Estado</th></tr></thead><tbody>@for (student of catalog().students; track student.id) {<tr><td>{{ student.name }}</td><td><select [(ngModel)]="status[student.id]"><option value="PRESENT">Presente</option><option value="ABSENT">Falta</option><option value="LATE">Tardanza</option></select></td></tr>}</tbody></table><button type="button" (click)="saveAll()">Guardar asistencia del día</button>@if (message()) {<p>{{ message() }}</p>}</section>}`,
  styles: [` .panel { background: var(--color-surface); border: 1px solid var(--color-border); border-radius: 8px; padding: 22px; margin-bottom: 18px; } .filters { display: grid; grid-template-columns: repeat(3, 1fr); gap: 14px; } label { display: grid; gap: 7px; color: var(--color-muted-text); } input, select { border: 1px solid var(--color-border); border-radius: 6px; padding: 10px; font: inherit; } table { width: 100%; border-collapse: collapse; } th, td { padding: 11px; border-bottom: 1px solid var(--color-border); text-align: left; } button { margin: 16px 10px 0 0; background: var(--color-primary); color: white; border: 0; border-radius: 6px; padding: 11px 16px; cursor: pointer; } button.outline { background: white; color: var(--color-primary); border: 1px solid var(--color-primary); } .summary { display:flex; gap:12px; margin-bottom:14px; flex-wrap:wrap; } .summary span { background:var(--color-surface); border:1px solid var(--color-border); border-radius:6px; padding:10px 14px; } @media(max-width:700px){.filters{grid-template-columns:1fr}} `],
})
export class AttendancePage {
  private readonly api = inject(ApiService); protected readonly catalog = signal<AcademicCatalog>({ grades: [], sections: [], courses: [], periods: [], students: [], literal_scale: [] }); protected readonly message = signal(''); protected readonly records = signal<AttendanceRecord[]>([]); protected level = ''; protected gradeId = ''; protected sectionId = ''; protected courseId = ''; protected periodId = ''; protected attendanceDate = new Date().toISOString().slice(0, 10); protected status: Record<string, string> = {};
  constructor() { this.loadCatalog(); }
  protected levels(): string[] { return [...new Set(this.catalog().grades.map((item) => item.level))]; }
  protected gradesForLevel() { return this.catalog().grades.filter((item) => item.level === this.level); }
  protected sectionsForGrade() { return this.catalog().sections.filter((item) => item.grade_id === this.gradeId); }
  protected gradeName(id: string) { return this.catalog().grades.find((item) => item.id === id)?.name ?? ''; }
  protected loadCatalog(): void { const filters: Record<string, string> = {}; if (this.gradeId) filters['grade_id'] = this.gradeId; if (this.sectionId) filters['section_id'] = this.sectionId; this.api.getAcademicCatalog(filters).subscribe({ next: (catalog) => { this.catalog.set(catalog); if (this.sectionId) { this.markAll('PRESENT'); this.loadRecords(); } } }); }
  protected loadRecords(): void { if (!this.sectionId || !this.courseId || !this.periodId) return; this.api.listAttendance({ grade_id: this.gradeId, section_id: this.sectionId, course_id: this.courseId, period_id: this.periodId, attendance_date: this.attendanceDate }).subscribe({ next: (records) => { this.records.set(records); records.forEach((record) => this.status[record.student_id] = record.status); } }); }
  protected count(value: string): number { return this.catalog().students.filter((student) => (this.status[student.id] ?? 'PRESENT') === value).length; }
  protected markAll(value: string): void { this.catalog().students.forEach((student) => this.status[student.id] = value); }
  protected saveAll(): void { if (!this.sectionId || !this.courseId || !this.periodId || !this.catalog().students.length) { this.message.set('Selecciona la sección, curso y periodo con alumnos disponibles.'); return; } let saved = 0; this.catalog().students.forEach((student) => this.api.createAttendance({ student_id: student.id, course_id: this.courseId, period_id: this.periodId, attendance_date: this.attendanceDate, status: this.status[student.id] ?? 'PRESENT' }).subscribe({ next: () => { saved += 1; this.message.set(`${saved} de ${this.catalog().students.length} asistencias guardadas.`); if (saved === this.catalog().students.length) this.loadRecords(); } })); }
}
