import { Component, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { AcademicCatalog, ApiService } from '../../core/services/api.service';
import { PageHeaderComponent } from '../../shared/components/page-header/page-header.component';

@Component({
  standalone: true,
  imports: [FormsModule, PageHeaderComponent],
  template: `<app-page-header title="Asistencia" description="Marca rápidamente las faltas del aula y guarda el día completo." /><section class="panel filters"><label>Curso<select [(ngModel)]="courseId"><option value="">Seleccionar curso</option>@for (course of catalog().courses; track course.id) {<option [value]="course.id">{{ course.name }}</option>}</select></label><label>Periodo<select [(ngModel)]="periodId"><option value="">Seleccionar periodo</option>@for (period of catalog().periods; track period.id) {<option [value]="period.id">{{ period.name }}</option>}</select></label><label>Fecha<input type="date" [(ngModel)]="attendanceDate" /></label></section><section class="panel"><div class="quick"><button type="button" (click)="markAll('PRESENT')">Todos presentes</button><button type="button" class="outline" (click)="markAll('ABSENT')">Todos ausentes</button></div><table><thead><tr><th>Estudiante</th><th>Estado</th></tr></thead><tbody>@for (student of catalog().students; track student.id) {<tr><td>{{ student.name }}</td><td><select [(ngModel)]="status[student.id]"><option value="PRESENT">Presente</option><option value="ABSENT">Falta</option><option value="LATE">Tardanza</option></select></td></tr>}</tbody></table><button type="button" (click)="saveAll()">Guardar asistencia del día</button>@if (message()) {<p>{{ message() }}</p>}</section>`,
  styles: [` .panel { background: var(--color-surface); border: 1px solid var(--color-border); border-radius: 8px; padding: 22px; margin-bottom: 18px; } .filters { display: grid; grid-template-columns: repeat(3, 1fr); gap: 14px; } label { display: grid; gap: 7px; color: var(--color-muted-text); } input, select { border: 1px solid var(--color-border); border-radius: 6px; padding: 10px; font: inherit; } table { width: 100%; border-collapse: collapse; } th, td { padding: 11px; border-bottom: 1px solid var(--color-border); text-align: left; } button { margin: 16px 10px 0 0; background: var(--color-primary); color: white; border: 0; border-radius: 6px; padding: 11px 16px; cursor: pointer; } button.outline { background: white; color: var(--color-primary); border: 1px solid var(--color-primary); } @media(max-width:700px){.filters{grid-template-columns:1fr}} `],
})
export class AttendancePage {
  private readonly api = inject(ApiService); protected readonly catalog = signal<AcademicCatalog>({ grades: [], sections: [], courses: [], periods: [], students: [] }); protected readonly message = signal(''); protected courseId = ''; protected periodId = ''; protected attendanceDate = new Date().toISOString().slice(0, 10); protected status: Record<string, string> = {};
  constructor() { this.api.getAcademicCatalog().subscribe({ next: (catalog) => { this.catalog.set(catalog); this.markAll('PRESENT'); } }); }
  protected markAll(value: string): void { this.catalog().students.forEach((student) => this.status[student.id] = value); }
  protected saveAll(): void { if (!this.courseId || !this.periodId) { this.message.set('Selecciona curso y periodo.'); return; } let saved = 0; this.catalog().students.forEach((student) => this.api.createAttendance({ student_id: student.id, course_id: this.courseId, period_id: this.periodId, attendance_date: this.attendanceDate, status: this.status[student.id] }).subscribe({ next: () => { saved += 1; this.message.set(`${saved} asistencias guardadas.`); } })); }
}
