import { DecimalPipe } from '@angular/common';
import { Component, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { AcademicCatalog, ApiService, RiskAlert } from '../../core/services/api.service';
import { PageHeaderComponent } from '../../shared/components/page-header/page-header.component';

@Component({
  standalone: true,
  imports: [FormsModule, PageHeaderComponent, DecimalPipe],
  template: `<app-page-header title="Reportes" description="Consulta rendimiento y asistencia por grado, sección y periodo." /><section class="filters"><label>Grado<select [(ngModel)]="gradeId" (ngModelChange)="load()"><option value="">Todos</option>@for (grade of catalog().grades; track grade.id) {<option [value]="grade.id">{{ grade.name }}</option>}</select></label><label>Sección<select [(ngModel)]="sectionId" (ngModelChange)="load()"><option value="">Todas</option>@for (section of catalog().sections; track section.id) {<option [value]="section.id">{{ section.name }}</option>}</select></label><label>Periodo<select [(ngModel)]="periodId" (ngModelChange)="load()"><option value="">Todos</option>@for (period of catalog().periods; track period.id) {<option [value]="period.id">{{ period.name }}</option>}</select></label></section>@if (loading()) {<p class="state">Cargando reporte...</p>} @else {<section class="cards"><article><span>Estudiantes</span><strong>{{ students().length }}</strong></article><article><span>Promedio</span><strong>{{ average() | number:'1.1-1' }}</strong></article><article><span>Asistencia</span><strong>{{ attendance() | number:'1.1-1' }}%</strong></article></section><section class="panel"><table><thead><tr><th>Estudiante</th><th>Promedio</th><th>Asistencia</th><th>Riesgo</th></tr></thead><tbody>@for (item of students(); track item.student_id) {<tr><td>{{ item.student_name }}</td><td>{{ item.average_score | number:'1.1-1' }}</td><td>{{ item.attendance_rate | number:'1.1-1' }}%</td><td>{{ item.risk_level }}</td></tr>}</tbody></table></section>}`,
  styles: [` .filters { display:grid; grid-template-columns:repeat(3,1fr); gap:14px; margin-bottom:18px; } label { display:grid; gap:7px; color:var(--color-muted-text); } select { padding:10px; border:1px solid var(--color-border); border-radius:6px; font:inherit; } .cards { display:grid; grid-template-columns:repeat(3,1fr); gap:16px; margin-bottom:18px; } article,.panel,.state { background:var(--color-surface); border:1px solid var(--color-border); border-radius:8px; padding:20px; } article { display:grid; gap:10px; } article span { color:var(--color-muted-text); } article strong { color:var(--color-primary); font-size:2rem; } table { width:100%; border-collapse:collapse; } th,td { padding:12px; border-bottom:1px solid var(--color-border); text-align:left; } @media(max-width:700px){.filters,.cards{grid-template-columns:1fr}} `],
})
export class ReportsPage {
  private readonly api = inject(ApiService);
  protected readonly catalog = signal<AcademicCatalog>({ grades: [], sections: [], courses: [], periods: [], students: [] });
  protected readonly students = signal<RiskAlert[]>([]); protected readonly loading = signal(true); protected readonly average = signal(0); protected readonly attendance = signal(0); protected gradeId = ''; protected sectionId = ''; protected periodId = '';
  constructor() { this.api.getAcademicCatalog().subscribe({ next: (catalog) => this.catalog.set(catalog) }); this.load(); }
  protected load(): void { this.loading.set(true); const filters: Record<string, string> = {}; if (this.gradeId) filters['grade_id'] = this.gradeId; if (this.sectionId) filters['section_id'] = this.sectionId; if (this.periodId) filters['period_id'] = this.periodId; this.api.getStudentReports(filters).subscribe({ next: (items) => { this.students.set(items); this.average.set(items.length ? items.reduce((sum, item) => sum + item.average_score, 0) / items.length : 0); this.attendance.set(items.length ? items.reduce((sum, item) => sum + item.attendance_rate, 0) / items.length : 0); this.loading.set(false); }, error: () => this.loading.set(false) }); }
}
